sudo: required

language: python
python:
  - "2.7"
  - "3.6"

install:
  - sudo apt-get install pandoc
  - pip install --upgrade pip tox pypandoc

script: tox .

notifications:
  email: false

deploy:
  provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASSWORD"

  on:
    tags: true

  distributions: "sdist bdist_wheel"
